hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra:job.num}
  job:
    chdir: true
  
  # Enable tab completion for config overrides
  help:
    app_name: stepwise-transformers
    header: |
      Stepwise Transformers: Interactive transformer learning with ClearML
      
      Examples:
        python scripts/train.py model=small_transformer training.batch_size=16
        python scripts/train.py training.learning_rate=1e-3 logging.project_name=my-experiment
  
  # Override configuration
  override_dirname: 
    kv_sep: '='
    item_sep: ','
    exclude_keys: []
