# Medium transformer configuration (default)
# @package model

d_model: 512
n_heads: 8
n_encoder_layers: 6
n_decoder_layers: 6
d_ff: 2048
dropout: 0.1
src_vocab_size: 32000
tgt_vocab_size: 32000
max_seq_length: 512
